AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: stage
      Tags:
        Key: "Owner"
        Value: "Andrea"

  PostBusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_post_bus.lambda_handler
      Runtime: python3.9
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref BusTimeTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /bustime
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          TABLE_NAME: !Ref BusTimeTable
      Tags:
        Key: "Owner"
        Value: "Andrea"

  GetBusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_get_bus.lambda_handler
      Runtime: python3.9
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref BusTimeTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /bustime
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          TABLE_NAME: !Ref BusTimeTable
      Tags:
        Key: "Owner"
        Value: "Andrea"

  BusTimeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "stop_code"
          AttributeType: "S"
        -
          AttributeName: "datetime"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "stop_code"
          KeyType: "HASH"
        -
          AttributeName: "datetime"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      Tags:
        - Key: "Owner"
          Value: "Andrea"
